---
name: test

on:
  workflow_dispatch:

jobs:
  Send_Note:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Python Install
        run: |
          python -m pip install --upgrade pip
          pip install Misskey.py

      - name: Test Note
        run: |
          python test.py
          cat test.txt

      - name: Update openapi.json
        run: |
          if ! git diff --exit-code --quiet
          then
           git add --update
            git config user.name github-actions
            git config user.email github-actions@github.com
            git commit -m "Update openapi.json"
            git push
          fi
