---
name: test

on:
  workflow_dispatch:

jobs:
  Send_Note:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Python Install
        run: |
          python -m pip install --upgrade pip
          pip install Misskey.py

      - name: Test Note
        run: |
          python test.py
          cat test.txt

      - name: Update test.txt
        run: |
          if ! git diff --exit-code --quiet
          then
           git add --update
            git config --global user.name ${{ secrets.YOUSER_NAME }}
            git config --global user.email ${{ secrets.MAIL_ADDRESS }}
            git remote set-url origin https://${{ secrets.MAIL_ADDRESS }}@github.com/${{ secrets.MAIL_ADDRESS }}/misskey_niconico_info_bot.git
            git commit -m "Update test.txt"
            git push
          fi
