---
name: test

on:
  workflow_dispatch:

jobs:
  Send_Note:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Python Install
        run: |
          python -m pip install --upgrade pip
          pip install Misskey.py

      - name: Test Note
        run: |
          python test.py
          cat test.txt

      - name: artifact upload
        uses: actions/upload-artifact@v2.2.0
        with:
          name: test
          # 保存するファイル
          path: test.txt
          # 保存期間（日）
          retention-days: 1
