---
name: test

on:
  push:
    branches-ignore:
      - "coverage"
  pull_request:
  workflow_dispatch:
    inputs:
      string_var:
        type: string
        description: 'string variable'
        required: false
        default: 'default string'
      choice_var:
        type: choice
        description: 'choice variable'
        required: false
        default: 'b'
        options:
          - 'a'
          - 'b'
          - 'c'
      boolean_var:
        type: boolean
        description: 'boolean variable'
        required: false
        default: false
      environment_var:
        type: environment
        description: 'enviroment variable'
        required: false
        default: prod
      number_var:
        type: number
        description: 'number variable'
        required: false
        default: 1
      test_type_var:
        type: test_type
        description: 'test_type variable'
        required: false
        default: abc

jobs:
  check_post-content:
    runs-on: ubuntu-latest

    steps:
    - run: echo Hello, world!
