---
name: test

on:
  workflow_dispatch:

jobs:
  Send_Note:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Python Install
        run: |
          python -m pip install --upgrade pip
          pip install Misskey.py

      - name: Test Note
        run: |
          python test.py
          cat test.txt

      - name: Commit and push if changed
        run: |-
          git diff
          git config --global user.name "commit test"
          git add -A
          git commit -m "Update test.txt" || exit 0
          git push
